name: Review

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  # find the branch name for 'pull_request' or on 'push' events
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  review-source-code:
    name: Review source code
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      # enable remote caching using turbo
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build-rpch
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Review formatting
        run: yarn format

      - name: Review linting
        run: cat /home/runner/work/RPCh/RPCh/apps/rpc-server/src/index.spec.ts && yarn lint --force

      - name: Review dependencies
        run: yarn depcheck

      - name: Run tests and coverage
        run: yarn test --ci
